services:
  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    ports:
      - "8082:8082"
    command: >
      java -jar /app/api-gateway.jar
    environment:
      SPRING_CLOUD_GATEWAY_ROUTES_0_ID: auth-service
      SPRING_CLOUD_GATEWAY_ROUTES_0_URI: http://auth-service:8080
      SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES: Path=/api/auth/**
      SPRING_CLOUD_GATEWAY_ROUTES_1_ID: email-service
      SPRING_CLOUD_GATEWAY_ROUTES_1_URI: http://email-service:8081
      SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES: Path=/api/email/**
    depends_on:
      - auth-service
      - email-service

  auth-service:
    container_name: auth-service
    build: ./auth-service
    ports:
      - "8080"
      - "5005"
      
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
    depends_on:
      - auth-db
      - rabbitmq
    command: >
      java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
          -jar /app/auth-service.jar

  email-db:
    container_name: email-db
    image: postgres:13-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${EMAIL_DB_NAME}
      POSTGRES_USER: ${EMAIL_DB_USER}
      POSTGRES_PASSWORD: ${EMAIL_DB_PASSWORD}
    volumes:
      - email-db-data:/var/lib/postgresql/data

  email-service:
    container_name: email-service
    build: ./email-service
    ports:
      - "8081"
    environment:
      EMAIL_SVC_DATASOURCE_URL: jdbc:postgresql://email-db:5432/${EMAIL_DB_NAME}
      EMAIL_SVC_DATASOURCE_USERNAME: ${EMAIL_DB_USER}
      EMAIL_SVC_DATASOURCE_PASSWORD: ${EMAIL_DB_PASSWORD}
      EMAIL_SVC_JPA_DDL_AUTO: update
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_SMTP_AUTH: ${MAIL_SMTP_AUTH}
      MAIL_SMTP_STARTTLS: ${MAIL_SMTP_STARTTLS}
    depends_on:
      - email-db
      - rabbitmq

  auth-db:
    container_name: auth-db
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - auth-db-data:/var/lib/postgresql/data

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"   # Web UI
      - "1025:1025"   # SMTP

volumes:
  auth-db-data:
  email-db-data:
